#!/bin/bash

python clean_simulations.py ./pCa_50/
python clean_simulations.py ./pCa_150/
python clean_simulations.py ./Cab_50/
python clean_simulations.py ./Cab_150/
python clean_simulations.py ./Jrel_50/
python clean_simulations.py ./Jrel_150/
python clean_simulations.py ./NCX_50/
python clean_simulations.py ./NCX_150/
python clean_simulations.py ./Juptake_50/
python clean_simulations.py ./Juptake_150/
python clean_simulations.py ./CaL_50/
python clean_simulations.py ./CaL_150/
python clean_simulations.py ./Jleak_50/
python clean_simulations.py ./Jleak_150/
python clean_simulations.py ./Cl_50/
python clean_simulations.py ./Cl_150/
python clean_simulations.py ./Kss_50/
python clean_simulations.py ./Kss_150/
python clean_simulations.py ./K1_50/
python clean_simulations.py ./K1_150/
python clean_simulations.py ./Kt_50/
python clean_simulations.py ./Kt_150/
python clean_simulations.py ./Kf_50/
python clean_simulations.py ./Kf_150/
python clean_simulations.py ./Ko_50/
python clean_simulations.py ./Ko_150/
python clean_simulations.py ./NaK_50/
python clean_simulations.py ./NaK_150/
python clean_simulations.py ./Na_50/
python clean_simulations.py ./Na_150/
python clean_simulations.py ./Nab_50/
python clean_simulations.py ./Nab_150/
python clean_simulations.py ./Kb_50/
python clean_simulations.py ./Kb_150/
python clean_simulations.py ./Naf_50/
python clean_simulations.py ./Naf_150/
python clean_simulations.py ./CHE_50/
python clean_simulations.py ./CHE_150/
python clean_simulations.py ./AE_50/
python clean_simulations.py ./AE_150/
python clean_simulations.py ./NCB_50/
python clean_simulations.py ./NCB_150/
python clean_simulations.py ./H_50/
python clean_simulations.py ./H_150/
python clean_simulations.py ./NHE_50/
python clean_simulations.py ./NHE_150/