#!/bin/bash

python clean_simulations.py ./pCa_0.5/
python clean_simulations.py ./pCa_1.5/
python clean_simulations.py ./Cab_0.5/
python clean_simulations.py ./Cab_1.5/
python clean_simulations.py ./Jrel_0.5/
python clean_simulations.py ./Jrel_1.5/
python clean_simulations.py ./NCX_0.5/
python clean_simulations.py ./NCX_1.5/
python clean_simulations.py ./Juptake_0.5/
python clean_simulations.py ./Juptake_1.5/
python clean_simulations.py ./CaL_0.5/
python clean_simulations.py ./CaL_1.5/
python clean_simulations.py ./Jleak_0.5/
python clean_simulations.py ./Jleak_1.5/
python clean_simulations.py ./Cl_0.5/
python clean_simulations.py ./Cl_1.5/
python clean_simulations.py ./Kss_0.5/
python clean_simulations.py ./Kss_1.5/
python clean_simulations.py ./K1_0.5/
python clean_simulations.py ./K1_1.5/
python clean_simulations.py ./Kt_0.5/
python clean_simulations.py ./Kt_1.5/
python clean_simulations.py ./Kf_0.5/
python clean_simulations.py ./Kf_1.5/
python clean_simulations.py ./Ko_0.5/
python clean_simulations.py ./Ko_1.5/
python clean_simulations.py ./NaK_0.5/
python clean_simulations.py ./NaK_1.5/
python clean_simulations.py ./Na_0.5/
python clean_simulations.py ./Na_1.5/
python clean_simulations.py ./Nab_0.5/
python clean_simulations.py ./Nab_1.5/
python clean_simulations.py ./Kb_0.5/
python clean_simulations.py ./Kb_1.5/
python clean_simulations.py ./Naf_0.5/
python clean_simulations.py ./Naf_1.5/
python clean_simulations.py ./CHE_0.5/
python clean_simulations.py ./CHE_1.5/
python clean_simulations.py ./AE_0.5/
python clean_simulations.py ./AE_1.5/
python clean_simulations.py ./NCB_0.5/
python clean_simulations.py ./NCB_1.5/
python clean_simulations.py ./H_0.5/
python clean_simulations.py ./H_1.5/
python clean_simulations.py ./NHE_0.5/
python clean_simulations.py ./NHE_1.5/